document:
  name: Titolo del progetto
  description: |
    Abstract ... Lorem ipsum dolor sit amet, consectetur 
    adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. 
    Ut enim ad minim veniam, quis nostrud 
    exercitation ullamco laboris nisi ut 
    aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in 
    voluptate velit esse cillum dolore eu
    fugiat nulla pariatur. Excepteur sint 
    occaecat cupidatat non proident, sunt in
    culpa qui officia deserunt mollit anim id 
    est laborum.    
  tags:
    - keywords / topic / hashtag relativi al progetto, uno per riga
    - valutazione comparativa
    - dati aperti
    - gestione del cambiamento
    - gestione documentale
    - gestione contributi
    - compatibilità licenze
